# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: kaidez - Tutorials & Articles about Web Development
email: ""
description: # this means to ignore newlines until "baseurl:"
  Web Development Tutorials for Beginners, Product Reviews, Rants and More from kaidez.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kaidez.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kaidez
github_username:  kaidez

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins: [jekyll-redirect-from, jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]

exclude:
  - Gemfile
  - Gemfile.lock
  - general_notes.md
  - image-minify/
  - js-build/
  - package.json
  - README.md
  - webpack.config.js
  - yarn.lock
  - .DS_Store
  - _includes/.DS_Store
  - _drafts
  - vendor

paginate: 10
paginate_path: "/blog/page/:num/"

author: Kai Gittens
name: Kai Gittens

social:
  name: Kai Gittens
  links:
    - https://twitter.com/kaidez
    - https://www.facebook.com/kaidezblog
    - https://www.linkedin.com/in/kaigittens/
    - https://plus.google.com/+KaiGittens
    - https://github.com/kaidez