[build]
  command = "npm run build"
  publish = "_site"

[dev]
  command = "npm start"
  port = 8080

# Cache node_modules between builds
[build.environment]
  NODE_VERSION = "18"

# Redirect rules (add any custom redirects you need)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404