name: Deploy kaidez.com

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Required permissions for GitHub Pages deployment
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0 # Fetch all history for all branches
      
      - name: Setup Node.js # Need to run npm scripts while running the workflow
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci # Use npm ci for clean install based on package-lock.json
      
      - name: Build kaidez.com
        run: npm run build:prod
      
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  notify-completion:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Report deployment status
        run: |
          if [ "${{ needs.build-and-deploy.result }}" == "success" ]; then
            echo "✅ Deployment successful!"
            echo "🚀 Site is now live at: https://kaidez.com"
            echo "📋 Summary:"
            echo "  - Built from main branch"
            echo "  - Deployed to GitHub Pages"
          else
            echo "❌ Deployment failed!"
            echo "Check the build logs for details."
          fi
